### ISSUE TITLE
dataset downloading problems

### ISSUE THREAD

**Issue by GinkgoX** [reganzm/Learn-Pytorch-And-Become-A-Data-Scientist#1]
Dear author:
     Could you give the link of the dataset download path? 
     Thanks a lot!!

**Comment by xiaoping2367** [comment]
麻烦提供配套的数据集，或者下载链接也行，感激不尽！！

**Comment by reganzm** [comment]
关注微信公众号：三角兽，后台回复pytorch获取。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "reganzm/Learn-Pytorch-And-Become-A-Data-Scientist"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月16日(星期一) 下午5:12
收件人:&nbsp;"reganzm/Learn-Pytorch-And-Become-A-Data-Scientist"<Learn-Pytorch-And-Become-A-Data-Scientist@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [reganzm/Learn-Pytorch-And-Become-A-Data-Scientist] dataset downloading problems (#1)





 
麻烦提供配套的数据集，或者下载链接也行，感激不尽！！
